[package]
name = "tari_utilities"
description = "A set of useful and commonly used utilities that are used in several places in the Tari project."
authors = ["The Tari Development Community"]
repository = "https://github.com/tari-project/tari"
homepage = "https://tari.com"
readme = "README.md"
license = "BSD-3-Clause"
version = "0.4.0"
edition = "2018"

[dependencies]
base58-monero = {version = "0.3.2", default-features = false}
base64 = "0.13.0"
bincode = "1.3.3"
bitflags = "1.3.2"
newtype-ops = "0.1.4"
rand = "0.8.4"
serde = {version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
thiserror = "1.0.30"

[dev-dependencies]
